name: SonarCloud Scan

on:
  push:
    branches:
      - main  # This can be the main branch or any branch you want to analyze

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install Sonar Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
          unzip sonar-scanner.zip -d $HOME
          echo "$HOME/sonar-scanner-4.6.0.2311-linux/bin" >> $GITHUB_PATH

      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token is automatically provided by GitHub Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Add this in your repository secrets (from SonarCloud)
        run: |
          sonar-scanner \
            -Dsonar.projectKey=tayyaabz_tayyaab \
            -Dsonar.organization=tayyaabz \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

